# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da4c1d2702e2cfc866d7007a58a289abb7bf000ef99c0a31e96d7917a0412d363fa23800f924955980a6d968bbbf543148e1a08ac616f083db870097af6d4882
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>

test:
  secret_key_base: 78c55f5b2dfaf665ac846b8cb52a20031af399e8eaf44f08cc4f4bd2ce1c78dc15e994cf8727dd2390c47a77b41213f05e76b1368fd2e6d7aca41b77760f8786
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: da4c1d2702e2cfc866d7007a58a289abb7bf000ef99c0a31e96d7917a0412d363fa23800f924955980a6d968bbbf543148e1a08ac616f083db870097af6d4882
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
